import "./globals.css";

export const metadata = {
  title: {
    default: "Home",
    template: "%s | Next",
  },
  description: "Generated by create next app",
  icons: { icon: "/icons/logo.png" },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
