export const metadata = {
  title: {
    default: "About",
  },
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <>
      <h1>About Page</h1>
    </>
  );
}
