import Counter from "@/app/components/Counter";

export const metadata = {
  title: {
    default: "Menu",
  },
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div className=" w-full h-screen">
      <h1>Menu Page</h1>
      <br />
      <Counter />
    </div>
  );
}
